baseURL = "https://example.com/"
languageCode = "en-gb"
title = "Hugo Theme - Prav"
theme = "hugo-theme-prav"


# If you want to track using GA or use disqus for comments, uncomment the 
# following and add the correct values
#googleanalytics = ""
#disqusShortname = ""

# The settings below are used throughout the theme.
# Please update!
[params]
    title = "Hugo Theme - Prav"
    tagline = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    author = "GuangyaoZhao"
    authorImgPath = "/img/author.png"
    authorBlurb = "Something about me"


# If you do not want a social icon, just comment it out
# Please update the example values!
[social]
    email = "zhaoguangyao1991@163.com"


# Set unsafe mode to allow markdownify to work with goldmark
# This is important. Please do not delete. It is used to re-render markdown
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true